// SPDX-License-Identifier: Apache-2.0
// Write the membrane's three tables as a module, from the three JSON files that own them.
//
// The membrane read those files with `node:fs` at module scope, which is a decision that
// looks like nothing and closes a door: a module that reads a file at import time cannot
// be imported by a browser, and the membrane is the one part of this application a window
// has to import in order to draw a row that came from the server. That is why req/803
// measures C3 at 0/16 -- not because the membrane is unfinished (it is built and it passed
// a live smoke against a real gx bed), but because no window could load it.
//
// So the JSON keeps being the source and stops being read at run time. This is the same
// shape `shell/tools/gen_routes.mjs` already uses on the same data, for the same reason,
// and it carries the same `--check` so a stale generated module fails a gate instead of
// being discovered in a window.
//
//   node tools/gen_tables.mjs           write it
//   node tools/gen_tables.mjs --check   fail if what is on disk is not what this writes

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const MEMBRANE = join(HERE, '..');

/** The three files, named once. The generated module and the freshness test both read this. */
export const SOURCES = Object.freeze({
  TABLE: 'route-table.json',
  COVERAGE: 'coverage.json',
  WIRE_FIELDS: 'wire-fields.json',
});

export const TARGET = join(MEMBRANE, 'src', 'tables.gen.mjs');

export function render() {
  const parts = Object.entries(SOURCES).map(([name, file]) => {
    const held = JSON.parse(readFileSync(join(MEMBRANE, file), 'utf8'));
    return `export const ${name} = ${JSON.stringify(held, null, 2)};\n`;
  });
  return `// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_tables.mjs from ${Object.values(SOURCES).join(', ')}. Do not edit.
//
// The JSON beside this file is still the source; this module is that JSON in the one
// form a browser can import. \`membrane/test/tables_gen.test.mjs\` fails if the two
// disagree, so editing the JSON without regenerating is a red suite and not a surprise
// in a window.

${parts.join('\n')}`;
}

if (process.argv[1] && process.argv[1].endsWith('gen_tables.mjs')) {
  const text = render();
  if (process.argv.includes('--check')) {
    const held = existsSync(TARGET) ? readFileSync(TARGET, 'utf8') : '';
    if (held !== text) {
      process.stderr.write('stale: membrane/src/tables.gen.mjs no longer matches the JSON beside it\n');
      process.exit(1);
    }
    process.stdout.write('tables are current\n');
  } else {
    writeFileSync(TARGET, text, 'utf8');
    process.stdout.write(`wrote ${TARGET}\n`);
  }
}
