// SPDX-License-Identifier: Apache-2.0
// Make the conformance gate (tools/conformance.mjs) fail on purpose, once per check,
// and confirm it notices -- the same shape shell/tools/negative.mjs uses for
// tools/gates.mjs (req/06 §3d: a gate not fired once does not close its DoD).
//
// The copy is the point: this runs against a scratch duplicate of the whole app tree,
// injects one fault per check into one module, reruns the gate against the copy (via
// `--root`), and requires the targeted check -- and only that module -- to fall. The
// working tree is never written to.
//
//   node tools/conformance_negative.mjs
//
// Exit 0 when every injection turned exactly what it targeted red. Exit 1 otherwise.

import { cpSync, mkdtempSync, readFileSync, writeFileSync, rmSync, unlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { execFileSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = join(HERE, '..');
const CONFORMANCE = join(HERE, 'conformance.mjs');

/** One fault per checkable slice, each the smallest thing that ought to be caught. */
const INJECTIONS = [
  {
    check: 'bench declaration present',
    module: 'membrane',
    said: 'delete the bench report',
    apply: (root) => { try { unlinkSync(join(root, 'membrane', '.bench', 'report.json')); } catch { /* absent is the point */ } },
  },
  {
    check: 'SPDX + English',
    module: 'membrane',
    said: 'strip the SPDX line from a shipped source file',
    apply: (root) => {
      const at = join(root, 'membrane', 'src', 'address.mjs');
      writeFileSync(at, readFileSync(at, 'utf8').replace('// SPDX-License-Identifier: Apache-2.0\n', ''));
    },
  },
  {
    check: 'generated-file rebuildable header',
    module: 'shell',
    said: 'strip the self-declaration banner from a generated file',
    apply: (root) => {
      const at = join(root, 'shell', 'demo', 'manifest.gen.mjs');
      writeFileSync(at, readFileSync(at, 'utf8').replace('// Generated by tools/gen_manifest.mjs. Do not edit: the folder is the source.\n', ''));
    },
  },
  {
    check: 'CRUD/ACTS declaration present',
    module: 'faces/ledger',
    said: 'remove the ACTS export from the declaration',
    apply: (root) => {
      const at = join(root, 'faces', 'ledger', 'declaration.mjs');
      writeFileSync(at, readFileSync(at, 'utf8').replace('export const ACTS', 'const RENAMED_ACTS_SO_THE_MARKER_IS_GONE'));
    },
  },
];

// execFileSync throws on nonzero exit (conformance.mjs exits 1 when anything falls),
// so both the clean baseline and each broken run need a catch that still recovers the
// JSON from stdout.
function runOutcome(root) {
  try {
    const stdout = execFileSync(process.execPath, [CONFORMANCE, '--root', root, '--json'], { encoding: 'utf8', stdio: 'pipe' });
    return JSON.parse(stdout);
  } catch (error) {
    if (error.stdout) return JSON.parse(error.stdout);
    throw error;
  }
}

const outcomes = [];
for (const injection of INJECTIONS) {
  const root = mkdtempSync(join(tmpdir(), 'gx-conformance-neg-'));
  try {
    for (const dir of ['membrane', 'shell', 'parts', 'faces', 'tools', 'req', 'docs']) {
      cpSync(join(APP, dir), join(root, dir), { recursive: true });
    }
    const clean = runOutcome(root);
    const cleanModule = clean.results.find((r) => r.module === injection.module);
    const cleanOk = cleanModule?.checks[injection.check]?.length === 0;

    injection.apply(root);
    const broken = runOutcome(root);
    const brokenModule = broken.results.find((r) => r.module === injection.module);
    const brokenMisses = brokenModule?.checks[injection.check] ?? [];

    // Collateral: any OTHER module x check that moved. A fault aimed at one module's
    // one check should not turn a different cell red.
    const collateral = [];
    for (const c of clean.results) {
      const b = broken.results.find((r) => r.module === c.module);
      for (const [name, misses] of Object.entries(c.checks)) {
        if (c.module === injection.module && name === injection.check) continue;
        const bmisses = b?.checks[name] ?? [];
        if (misses.length !== bmisses.length) collateral.push(`${c.module} / ${name}`);
      }
    }

    const landed = cleanOk && brokenMisses.length > 0 && collateral.length === 0;
    outcomes.push({ check: injection.check, module: injection.module, said: injection.said, landed, cleanOk, brokenMisses, collateral });
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

for (const o of outcomes) {
  console.log(`${o.landed ? 'LANDED' : 'FELL  '}  ${o.module} / ${o.check}  -- ${o.said}`);
  if (!o.cleanOk) console.log('        clean baseline was already failing this check -- the round proves nothing');
  if (o.landed) for (const m of o.brokenMisses) console.log(`        turned red: ${m}`);
  if (o.collateral.length) console.log(`        collateral: ${o.collateral.join(', ')}`);
}
const failed = outcomes.filter((o) => !o.landed);
console.log(`\nrounds ${outcomes.length}  landed ${outcomes.length - failed.length}`);
console.log(failed.length === 0
  ? 'conformance live rounds: every injected fault turned its own check red, nothing else moved'
  : 'conformance live rounds: a round did not turn its target, or moved something it was not aimed at');
process.exitCode = failed.length === 0 ? 0 : 1;
