// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_manifest.mjs. Do not edit: the folder is the source.

export const MANIFEST = {
  "faces": [
    {
      "id": "floor-a",
      "title": "Floor A",
      "place": "bottom",
      "purpose": "read",
      "rail": true,
      "consumes": [],
      "condition": "plain",
      "leastWidth": 200
    },
    {
      "id": "margin-a",
      "title": "Margin A",
      "place": "right",
      "purpose": "read",
      "rail": true,
      "consumes": [],
      "condition": "plain",
      "leastWidth": 200
    },
    {
      "id": "probe-a",
      "title": "Probe A",
      "place": "left",
      "purpose": "find",
      "rail": true,
      "consumes": [],
      "condition": "plain",
      "leastWidth": 200
    },
    {
      "id": "probe-b",
      "title": "Probe B",
      "place": "left",
      "purpose": "find",
      "rail": true,
      "consumes": [],
      "condition": "plain",
      "leastWidth": 200
    },
    {
      "id": "sheet-a",
      "title": "Sheet A",
      "place": "stage",
      "purpose": "read",
      "rail": true,
      "consumes": [
        "get_healthz"
      ],
      "condition": "plain",
      "leastWidth": 200
    },
    {
      "id": "sheet-b",
      "title": "Sheet B",
      "place": "stage",
      "purpose": "read",
      "rail": true,
      "consumes": [],
      "condition": "held",
      "leastWidth": 200
    },
    {
      "id": "sheet-c",
      "title": "Sheet C",
      "place": "stage",
      "purpose": "read",
      "rail": true,
      "consumes": [],
      "condition": "plain",
      "leastWidth": 200
    }
  ]
};

export default MANIFEST;
