// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_manifest.mjs. Do not edit: the folder is the source.
import * as face0 from './faces/floor-a/index.mjs';
import * as face1 from './faces/margin-a/index.mjs';
import * as face2 from './faces/probe-a/index.mjs';
import * as face3 from './faces/probe-b/index.mjs';
import * as face4 from './faces/sheet-a/index.mjs';
import * as face5 from './faces/sheet-b/index.mjs';
import * as face6 from './faces/sheet-c/index.mjs';

export const MODULES = new Map([
  ['floor-a', face0],
  ['margin-a', face1],
  ['probe-a', face2],
  ['probe-b', face3],
  ['sheet-a', face4],
  ['sheet-b', face5],
  ['sheet-c', face6],
]);

export default MODULES;
