// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_routes.mjs from the membrane's route table. Do not edit.

export const ROUTES = [
  {
    "name": "get_attach_sources",
    "verb": "GET",
    "path": "/attach-sources",
    "kind": "list"
  },
  {
    "name": "post_attach_sources",
    "verb": "POST",
    "path": "/attach-sources",
    "kind": "single"
  },
  {
    "name": "get_attach_sources_id",
    "verb": "GET",
    "path": "/attach-sources/{id}",
    "kind": "single"
  },
  {
    "name": "post_candidates",
    "verb": "POST",
    "path": "/candidates",
    "kind": "single"
  },
  {
    "name": "get_candidates",
    "verb": "GET",
    "path": "/candidates",
    "kind": "list"
  },
  {
    "name": "get_candidates_id",
    "verb": "GET",
    "path": "/candidates/{id}",
    "kind": "single"
  },
  {
    "name": "post_candidates_id_verify",
    "verb": "POST",
    "path": "/candidates/{id}/verify",
    "kind": "single"
  },
  {
    "name": "post_candidates_id_commit",
    "verb": "POST",
    "path": "/candidates/{id}/commit",
    "kind": "single"
  },
  {
    "name": "post_candidates_id_escalation",
    "verb": "POST",
    "path": "/candidates/{id}/escalation",
    "kind": "single"
  },
  {
    "name": "post_candidates_id_cancel",
    "verb": "POST",
    "path": "/candidates/{id}/cancel",
    "kind": "single"
  },
  {
    "name": "post_transformations_id_undo",
    "verb": "POST",
    "path": "/transformations/{id}/undo",
    "kind": "single"
  },
  {
    "name": "post_transformations_id_replay",
    "verb": "POST",
    "path": "/transformations/{id}/replay",
    "kind": "single"
  },
  {
    "name": "get_transformations_id",
    "verb": "GET",
    "path": "/transformations/{id}",
    "kind": "single"
  },
  {
    "name": "get_transformations",
    "verb": "GET",
    "path": "/transformations",
    "kind": "list"
  },
  {
    "name": "get_escalations",
    "verb": "GET",
    "path": "/escalations",
    "kind": "list"
  },
  {
    "name": "get_receipts_tid",
    "verb": "GET",
    "path": "/receipts/{tid}",
    "kind": "single"
  },
  {
    "name": "get_ledger_proof",
    "verb": "GET",
    "path": "/ledger/proof",
    "kind": "single"
  },
  {
    "name": "get_ledger_checkpoint",
    "verb": "GET",
    "path": "/ledger/checkpoint",
    "kind": "single"
  },
  {
    "name": "get_ledger_consistency",
    "verb": "GET",
    "path": "/ledger/consistency",
    "kind": "single"
  },
  {
    "name": "get_stream",
    "verb": "GET",
    "path": "/stream",
    "kind": "stream"
  },
  {
    "name": "post_verdict_checkpoints",
    "verb": "POST",
    "path": "/verdict-checkpoints",
    "kind": "single"
  },
  {
    "name": "get_verdict_checkpoints",
    "verb": "GET",
    "path": "/verdict-checkpoints",
    "kind": "list"
  },
  {
    "name": "get_verdict_checkpoints_window_end",
    "verb": "GET",
    "path": "/verdict-checkpoints/{window_end}",
    "kind": "single"
  },
  {
    "name": "get_healthz",
    "verb": "GET",
    "path": "/healthz",
    "kind": "single"
  }
];

export default ROUTES;
