// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_manifest.mjs. Do not edit: the folder is the source.

export const MANIFEST = {
  "faces": [
    {
      "id": "atlas",
      "title": "Atlas",
      "place": "stage",
      "purpose": "read",
      "rail": true,
      "consumes": [
        "get_transformations"
      ],
      "condition": "plain",
      "leastWidth": 320
    },
    {
      "id": "graph",
      "title": "Graph",
      "place": "stage",
      "purpose": "find",
      "rail": true,
      "consumes": [
        "get_transformations"
      ],
      "condition": "plain",
      "leastWidth": 320
    },
    {
      "id": "held",
      "title": "Held",
      "place": "right",
      "purpose": "read",
      "rail": true,
      "consumes": [
        "get_candidates",
        "post_candidates_id_commit",
        "post_candidates_id_cancel",
        "post_candidates_id_escalation",
        "post_transformations_id_undo"
      ],
      "condition": "held",
      "leastWidth": 320
    },
    {
      "id": "ledger",
      "title": "Ledger",
      "place": "stage",
      "purpose": "read",
      "rail": true,
      "consumes": [
        "get_transformations",
        "get_candidates",
        "get_ledger_consistency",
        "post_candidates_id_commit",
        "post_candidates_id_cancel",
        "post_candidates_id_escalation",
        "post_transformations_id_undo"
      ],
      "condition": "plain",
      "leastWidth": 320
    },
    {
      "id": "notice",
      "title": "Notice",
      "place": "bottom",
      "purpose": "read",
      "rail": true,
      "consumes": [],
      "condition": "plain",
      "leastWidth": 320,
      "leastHeight": 260
    },
    {
      "id": "receipt",
      "title": "Receipt",
      "place": "stage",
      "purpose": "read",
      "rail": true,
      "consumes": [
        "get_transformations_id",
        "get_receipts_tid"
      ],
      "condition": "plain",
      "leastWidth": 320
    }
  ]
};

export default MANIFEST;
