// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_manifest.mjs. Do not edit: the folder is the source.
import * as face0 from '../../faces/atlas/index.mjs';
import * as face1 from '../../faces/graph/index.mjs';
import * as face2 from '../../faces/held/index.mjs';
import * as face3 from '../../faces/ledger/index.mjs';
import * as face4 from '../../faces/notice/index.mjs';
import * as face5 from '../../faces/receipt/index.mjs';

export const MODULES = new Map([
  ['atlas', face0],
  ['graph', face1],
  ['held', face2],
  ['ledger', face3],
  ['notice', face4],
  ['receipt', face5],
]);

export default MODULES;
