// SPDX-License-Identifier: Apache-2.0
// Read the faces folder, write the manifest and the module map.
//
// A browser cannot list a directory, so somebody has to. The point of having a machine do
// it is not convenience: it is that "delete a face's folder and it disappears from the
// rail" becomes a thing that can be run rather than a thing that is claimed. A
// hand-written list would pass every review and would be exactly the list that drifts.
//
//   node tools/gen_manifest.mjs [--faces <dir>] [--out <dir>] [--drop <id>] [--check]
//
// --drop is for the negative control: regenerate without one face and assert it is gone
//   from the frame without the shell being edited.
// --check writes nothing and exits 1 when the generated files are out of date.

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const DEMO = join(HERE, '..', 'demo');

const argOf = (name, fallback) => {
  const at = process.argv.indexOf(name);
  return at === -1 ? fallback : process.argv[at + 1];
};

const facesDir = argOf('--faces', join(DEMO, 'faces'));
const outDir = argOf('--out', DEMO);
const dropped = process.argv.filter((a, i) => process.argv[i - 1] === '--drop');
const checkOnly = process.argv.includes('--check');

const HEAD = `// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_manifest.mjs. Do not edit: the folder is the source.
`;

function read() {
  const ids = readdirSync(facesDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((id) => !dropped.includes(id))
    .filter((id) => existsSync(join(facesDir, id, 'FACE.json')))
    .sort();
  const faces = ids.map((id) => {
    const declared = JSON.parse(readFileSync(join(facesDir, id, 'FACE.json'), 'utf8'));
    if (declared.id !== id) {
      throw new Error(`${id}/FACE.json calls itself "${declared.id}"; the folder is the name`);
    }
    return declared;
  });
  return { ids, faces };
}

function texts({ ids, faces }) {
  const manifest = `${HEAD}
export const MANIFEST = ${JSON.stringify({ faces }, null, 2)};

export default MANIFEST;
`;
  const from = (id) => {
    const path = relative(outDir, join(facesDir, id, 'index.mjs')).split('\\').join('/');
    return path.startsWith('.') ? path : `./${path}`;
  };
  const imports = ids.map((id, i) => `import * as face${i} from '${from(id)}';`).join('\n');
  const pairs = ids.map((id, i) => `  ['${id}', face${i}],`).join('\n');
  const modules = `${HEAD}${imports}

export const MODULES = new Map([
${pairs}
]);

export default MODULES;
`;
  return { manifest, modules };
}

const found = read();
const made = texts(found);
const targets = [
  [join(outDir, 'manifest.gen.mjs'), made.manifest],
  [join(outDir, 'modules.gen.mjs'), made.modules],
];

if (checkOnly) {
  const stale = targets.filter(([path, text]) => !existsSync(path) || readFileSync(path, 'utf8') !== text);
  if (stale.length > 0) {
    for (const [path] of stale) process.stderr.write(`stale: ${relative(HERE, path)}\n`);
    process.exit(1);
  }
  process.stdout.write(`manifest is current: ${found.ids.length} faces\n`);
} else {
  for (const [path, text] of targets) writeFileSync(path, text, 'utf8');
  process.stdout.write(`${found.ids.length} faces: ${found.ids.join(', ')}\n`);
}
