// SPDX-License-Identifier: Apache-2.0
// Write the demo's list of membrane method names, taken from the membrane.
//
// The demo runs against a stand-in rather than a server, and a stand-in whose methods
// were typed by hand is a stand-in that agrees with whatever the shell expects. So the
// names come from `tableRows` on the membrane's own public surface, which derives them
// from the route table, which is extracted from the crate that serves them. The stand-in
// can be wrong about what a route answers; it cannot be wrong about which routes exist.

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { tableRows } from '../../membrane/src/index.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const rows = tableRows().map((row) => ({ name: row.name, verb: row.verb, path: row.path, kind: row.kind }));

const text = `// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_routes.mjs from the membrane's route table. Do not edit.

export const ROUTES = ${JSON.stringify(rows, null, 2)};

export default ROUTES;
`;

const target = join(HERE, '..', 'demo', 'routes.gen.mjs');
if (process.argv.includes('--check')) {
  const held = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (held !== text) {
    process.stderr.write('stale: demo/routes.gen.mjs no longer matches the membrane\n');
    process.exit(1);
  }
  process.stdout.write(`routes are current: ${rows.length}\n`);
} else {
  writeFileSync(target, text, 'utf8');
  process.stdout.write(`${rows.length} routes\n`);
}
