// SPDX-License-Identifier: Apache-2.0
// Reads the stylesheet of record once, at build time, and writes the module the
// browser actually loads.
//
// tokens.mjs used to call fs.readFileSync at import time, which works in a Node test
// and breaks the moment a face is loaded into a real window: a browser has no
// node:fs to resolve (req/02 W15). The read still happens in exactly one place -- it
// only moves from "every time a runtime module is imported" to "once, here, before
// anything ships" -- and what it produces carries its own proof that it has not gone
// stale: a SHA-256 of the bytes it read, stamped into the header of the file it
// writes. parts/test/tokens-generated.test.mjs re-reads the canonical file itself, at
// test time, and fails the moment that digest stops matching -- so a stylesheet
// edited without a regenerate is caught rather than silently served from a stale
// mirror.
//
// Run it directly whenever ui_proto/ui/tokens.css changes:
//   node parts/tools/generate-tokens.mjs
// The drift gate is what tells you when you forgot.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { tokenSourceRealPath, sha256Hex, TOKEN_SOURCE_RELATIVE } from './token-source.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const GENERATED_PATH = path.resolve(HERE, '../generated/tokens.generated.mjs');

export function generate() {
  const sourcePath = tokenSourceRealPath();
  const text = fs.readFileSync(sourcePath, 'utf8');
  const digest = sha256Hex(text);
  const generatedAt = new Date().toISOString();
  const body = `// SPDX-License-Identifier: Apache-2.0
// AUTO-GENERATED by parts/tools/generate-tokens.mjs -- do not hand-edit.
//
// A build-time mirror of the one stylesheet of record, produced so that runtime code
// (which a real browser loads with no node:fs available, req/02 W15) can read the
// tokens without touching a disk. The mirror is provably fresh, not merely claimed
// fresh: parts/test/tokens-generated.test.mjs re-reads the canonical file at test
// time and fails the moment the digest below stops matching it.
//
// source:    ${TOKEN_SOURCE_RELATIVE} (resolved from parts/tools at generation time)
// sha256:    ${digest}
// generated: ${generatedAt}

export const TOKEN_SOURCE_RELATIVE = ${JSON.stringify(TOKEN_SOURCE_RELATIVE)};
export const TOKEN_SOURCE_SHA256 = ${JSON.stringify(digest)};
export const TOKEN_GENERATED_AT = ${JSON.stringify(generatedAt)};
export const TOKEN_SOURCE_TEXT = ${JSON.stringify(text)};
`;
  fs.mkdirSync(path.dirname(GENERATED_PATH), { recursive: true });
  fs.writeFileSync(GENERATED_PATH, body, 'utf8');
  return {
    path: GENERATED_PATH, sha256: digest, generatedAt, bytes: Buffer.byteLength(body),
  };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const result = generate();
  process.stdout.write(`${result.path} (${result.bytes} bytes, sha256 ${result.sha256})\n`);
}
