// SPDX-License-Identifier: Apache-2.0
// Reads what this build IS, once, and writes the module a face can draw it from.
//
// req/784 A-11 / adoption #5: the surface states its own render cost and its own build
// on every screen, for every reader, forever. The reference set is the argument -- one
// product's own pages report 718ms on one build and 82ms on another, and a reader can
// see the ninefold improvement with no dashboard and no report to go and find. Our own
// 5原則 ② asks for a runtime figure that does not rot; a number on the screen is the
// only kind that cannot.
//
// A face cannot read any of this for itself. It has no node:fs (req/02 W15), it may
// import nothing but its own binding, and it must not invent a number -- so the two
// facts that are not measured in the window (which commit this is, and what the suite
// last said) are stamped here at build time and the two that ARE measurable in the
// window (how long this face took to build its tree, and what it read) are passed in by
// the caller at draw time.
//
// Honesty rules this generator holds rather than assumes:
//   - A field it could not read is written as null, and the footer draws a dash for a
//     null (req/784 L-04: a dash is a typed absence, a zero is a measurement). It is
//     never filled with a plausible number.
//   - The suite figures are only ever what a caller passed on the command line, with
//     the moment they were passed stamped beside them, because this tool does not run
//     the suite and must not appear to have.
//   - The commit is the one this file was generated against, which is the commit
//     BEFORE the commit that carries the file. That is stated in the generated header
//     rather than rounded away.
//
//   node parts/tools/generate-build.mjs [--suite <tests>] [--failed <count>]

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const BUILD_PATH = path.resolve(HERE, '../generated/build.generated.mjs');
export const REPO = path.resolve(HERE, '../..');

export const BUILD_MESSAGES = {
  NO_COMMIT: 'git could not be asked what this build is, so the commit is null and the footer will draw a dash',
};

/** The short hash of the commit this generate ran against, or null if git said nothing. */
export function readCommit(cwd = REPO) {
  try {
    return execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd, encoding: 'utf8' }).trim() || null;
  } catch {
    return null;
  }
}

/** Whether the tree had uncommitted changes when this ran -- a build that is not exactly its commit says so. */
export function readDirty(cwd = REPO) {
  try {
    return execFileSync('git', ['status', '--porcelain'], { cwd, encoding: 'utf8' }).trim().length > 0;
  } catch {
    return null;
  }
}

export function numberOrNull(value) {
  if (value === undefined || value === null || value === '') return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

export function render({
  commit, dirty, at, suiteTests, suiteFailed, suiteAt,
}) {
  const j = (v) => JSON.stringify(v ?? null);
  return `// SPDX-License-Identifier: Apache-2.0
// AUTO-GENERATED by parts/tools/generate-build.mjs -- do not hand-edit.
//
// What this build is, for the footer every face draws (req/784 A-11, adoption #5).
//
// \`commit\` is the commit this file was generated AGAINST, which is the one before the
// commit that carries the file. A field that could not be read is null and is drawn as
// a dash, never as a zero: a zero is a measurement and a dash is the absence of one.
// \`suiteTests\`/\`suiteFailed\` are whatever a caller passed on the command line, stamped
// with the moment they were passed -- this generator does not run the suite.

export const BUILD = Object.freeze({
  commit: ${j(commit)},
  dirty: ${j(dirty)},
  at: ${j(at)},
  suiteTests: ${j(suiteTests)},
  suiteFailed: ${j(suiteFailed)},
  suiteAt: ${j(suiteAt)},
});

export default BUILD;
`;
}

export function generate(argv = []) {
  const arg = (name) => {
    const at = argv.indexOf(name);
    return at === -1 ? null : argv[at + 1];
  };
  const suiteTests = numberOrNull(arg('--suite'));
  const suiteFailed = numberOrNull(arg('--failed'));
  const now = new Date().toISOString();
  const body = render({
    commit: readCommit(),
    dirty: readDirty(),
    at: now,
    suiteTests,
    suiteFailed,
    suiteAt: suiteTests === null && suiteFailed === null ? null : now,
  });
  fs.mkdirSync(path.dirname(BUILD_PATH), { recursive: true });
  fs.writeFileSync(BUILD_PATH, body, 'utf8');
  return { path: BUILD_PATH, bytes: Buffer.byteLength(body) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  const made = generate(process.argv.slice(2));
  process.stdout.write(`${made.path} (${made.bytes} bytes)\n`);
}
