// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_tables.mjs from route-table.json, coverage.json, wire-fields.json. Do not edit.
//
// The JSON beside this file is still the source; this module is that JSON in the one
// form a browser can import. `membrane/test/tables_gen.test.mjs` fails if the two
// disagree, so editing the JSON without regenerating is a red suite and not a surprise
// in a window.

export const TABLE = {
  "note": "The wire half (base_path, verb, path) is extracted from the crate by tools/route_table_from_crate.mjs and is compared against it on every test run. The declared half of each row carries its own source reference. Nothing here is copied from any UI tree; the paths are the server's own spelling.",
  "base_path": "/v1",
  "base_path_source": "glovrex/crates/gx-api/src/lib.rs:80",
  "router_source": "glovrex/crates/gx-api/src/lib.rs:548-621",
  "auth_source": "glovrex/crates/gx-api/src/auth.rs:166-180 (header `authorization`, scheme `Bearer `, every route but /healthz)",
  "idempotency_source": "glovrex/crates/gx-api/src/handlers.rs:323 (`idempotency-key`), read at :917 and :1339; plus attach_sources.rs register() which reads the same header into its own replay cache (req/824 A4, absorbed req/822_c6). CAUTION (named, not fixed): the membrane's stableKey derives from method name + path id only -- it has no body axis -- so a caller sending two different register bodies through the membrane would collide into IDEMPOTENCY_CONFLICT. No face consumes post_attach_sources today; the hazard is carried in req/822_c6 rather than silently shipped into a caller.",
  "page_source": "glovrex/crates/gx-api/src/list.rs:57-70 (limit 1..=200 default 50, opaque cursor); verdict_checkpoints.rs:78-84,249-253 (integer cursor, `total`)",
  "routes": [
    {
      "verb": "GET",
      "path": "/attach-sources",
      "effect": "read",
      "kind": "list",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": "index",
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "POST",
      "path": "/attach-sources",
      "effect": "write",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "accepts",
      "cursor": null,
      "actor": "none",
      "accepts_body": true
    },
    {
      "verb": "GET",
      "path": "/attach-sources/{id}",
      "effect": "read",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "POST",
      "path": "/candidates",
      "effect": "write",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "required",
      "accepts_body": true
    },
    {
      "verb": "GET",
      "path": "/candidates",
      "effect": "read",
      "kind": "list",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": "opaque",
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/candidates/{id}",
      "effect": "read",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "POST",
      "path": "/candidates/{id}/verify",
      "effect": "write",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": true
    },
    {
      "verb": "POST",
      "path": "/candidates/{id}/commit",
      "effect": "write",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "accepts",
      "cursor": null,
      "actor": "none",
      "accepts_body": true
    },
    {
      "verb": "POST",
      "path": "/candidates/{id}/escalation",
      "effect": "write",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "required",
      "accepts_body": true
    },
    {
      "verb": "POST",
      "path": "/candidates/{id}/cancel",
      "effect": "write",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "required",
      "accepts_body": true
    },
    {
      "verb": "POST",
      "path": "/transformations/{id}/undo",
      "effect": "write",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "accepts",
      "cursor": null,
      "actor": "optional",
      "accepts_body": true
    },
    {
      "verb": "POST",
      "path": "/transformations/{id}/replay",
      "effect": "read",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": true
    },
    {
      "verb": "GET",
      "path": "/transformations/{id}",
      "effect": "read",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/transformations",
      "effect": "read",
      "kind": "list",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": "opaque",
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/escalations",
      "effect": "read",
      "kind": "list",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": "opaque",
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/receipts/{tid}",
      "effect": "read",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/ledger/proof",
      "effect": "read",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/ledger/checkpoint",
      "effect": "read",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/ledger/consistency",
      "effect": "read",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/stream",
      "effect": "read",
      "kind": "stream",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "POST",
      "path": "/verdict-checkpoints",
      "effect": "write",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": true
    },
    {
      "verb": "GET",
      "path": "/verdict-checkpoints",
      "effect": "read",
      "kind": "list",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": "index",
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/verdict-checkpoints/{window_end}",
      "effect": "read",
      "kind": "single",
      "auth": "bearer",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    },
    {
      "verb": "GET",
      "path": "/healthz",
      "effect": "read",
      "kind": "single",
      "auth": "none",
      "idempotency": "none",
      "cursor": null,
      "actor": "none",
      "accepts_body": false
    }
  ]
};

export const COVERAGE = {
  "note": "What the faces declare they call and draw. Membership in the three ledgers is NOT written here -- it is computed from this file against the route table and the field domain. The terminal face (glovrex_app/terminal/, req/946) has landed and is the first entry in `consumed`/`drawn`: its registration below is machine-checked against its own exports (`READS`/`STREAM`/`SUBJECT` in terminal/tui.mjs, `COLUMNS` in terminal/roles.mjs) by membrane/test/face_coverage.test.mjs (req/967 §4-2), not hand-guessed -- run that suite after touching any of them. As each face lands it adds itself to `consumed`/`drawn`, and its reason below must be removed in the same change or the gate goes red for keeping a stale explanation.",
  "consumed": {
    "get_healthz": [
      "terminal"
    ],
    "get_transformations": [
      "terminal"
    ],
    "get_candidates": [
      "terminal"
    ],
    "get_escalations": [
      "terminal"
    ],
    "get_stream": [
      "terminal"
    ]
  },
  "drawn": [
    "get_transformations.items"
  ],
  "requested": [],
  "reasons": {
    "NOT_CONSUMED": {
      "get_attach_sources": {
        "tag": "undesigned",
        "note": "attach-source registry (req/824 A4, crate commit 16863593, absorbed req/822_c6); no face is built"
      },
      "post_attach_sources": {
        "tag": "undesigned",
        "note": "as above; and the membrane's body-less idempotency key would collide two different register bodies -- named in route-table.json's idempotency_source before any face may consume this"
      },
      "get_attach_sources_id": {
        "tag": "undesigned",
        "note": "attach-source registry; no face is built"
      },
      "post_candidates": {
        "tag": "undesigned",
        "note": "no face proposes a change yet"
      },
      "get_candidates_id": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "post_candidates_id_verify": {
        "tag": "undesigned",
        "note": "asking twice is not ruled on; whether a second verify is a new question is open"
      },
      "post_candidates_id_commit": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "post_candidates_id_escalation": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "post_candidates_id_cancel": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "post_transformations_id_undo": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "post_transformations_id_replay": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "get_transformations_id": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "get_receipts_tid": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "get_ledger_proof": {
        "tag": "unimplemented",
        "note": "the input to offline re-verification; a face for it needs a verifier this app does not carry"
      },
      "get_ledger_checkpoint": {
        "tag": "unimplemented",
        "note": "as ledger/proof"
      },
      "get_ledger_consistency": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "post_verdict_checkpoints": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "get_verdict_checkpoints": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "get_verdict_checkpoints_window_end": {
        "tag": "undesigned",
        "note": "no face is built"
      }
    },
    "NOT_DRAWN": {
      "get_candidates.items": {
        "tag": "undesigned",
        "note": "the terminal face reads this route (`consumed`, via READS) so its denominator counts and its disclosure name it, but the face draws rows only from its declared SUBJECT (get_transformations); whether a second panel ever draws candidates is undesigned"
      },
      "get_candidates.next_cursor": {
        "tag": "undesigned",
        "note": "paging is folded inside the membrane (port.fold); a face may never see this member directly"
      },
      "get_transformations.next_cursor": {
        "tag": "undesigned",
        "note": "as above -- folded internally by port.fold; unlike .items, the cursor itself is never handed to the renderer"
      },
      "get_escalations.items": {
        "tag": "undesigned",
        "note": "as get_candidates.items -- read by the terminal face, not drawn; get_transformations is the only SUBJECT"
      },
      "get_escalations.next_cursor": {
        "tag": "undesigned",
        "note": "as get_candidates.next_cursor -- folded internally"
      },
      "get_verdict_checkpoints.items": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "get_verdict_checkpoints.next_cursor": {
        "tag": "undesigned",
        "note": "as above"
      },
      "get_verdict_checkpoints.total": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "get_ledger_consistency.consistent": {
        "tag": "undesigned",
        "note": "no face is built; when one is, this word may not be drawn as offline verification"
      },
      "get_ledger_consistency.checked_from": {
        "tag": "undesigned",
        "note": "no face is built"
      },
      "get_ledger_consistency.checked_to": {
        "tag": "undesigned",
        "note": "no face is built"
      }
    },
    "NOT_A_ROUTE": {}
  }
};

export const WIRE_FIELDS = {
  "note": "The domain NOT_DRAWN is computed against. Only members read in the crate are listed; response bodies assembled in handlers.rs were not read, and that hole is declared here rather than filled from a second-hand list. The ledger therefore reports a real denominator that is smaller than the eventual one, which is the honest shape: a domain that looks complete and is not would make NOT_DRAWN look small for the wrong reason.",
  "hole": "gx-api/src/handlers.rs response bodies unread; receipts, transformation views, verify outcomes and undo outcomes contribute no fields to this domain yet. Narrowed req/822_c6: the LIST-ROW members of get_candidates/get_transformations (transformation/state/verdict/enforced/created_at/actor/scope, + superseded_by/inverse_status/rollback) were dumped from a live engine and are carried through the declared projection in src/vocabulary.mjs; they are still not entries in this route.field domain, which stays page-level -- extending the domain to item members is a design of its own and is named in req/822_c6 rather than done quietly here",
  "fields": [
    {
      "route": "get_candidates",
      "field": "items",
      "source": "gx-api/src/list.rs:151"
    },
    {
      "route": "get_candidates",
      "field": "next_cursor",
      "source": "gx-api/src/list.rs:156"
    },
    {
      "route": "get_transformations",
      "field": "items",
      "source": "gx-api/src/list.rs:151"
    },
    {
      "route": "get_transformations",
      "field": "next_cursor",
      "source": "gx-api/src/list.rs:156"
    },
    {
      "route": "get_escalations",
      "field": "items",
      "source": "gx-api/src/list.rs:151"
    },
    {
      "route": "get_escalations",
      "field": "next_cursor",
      "source": "gx-api/src/list.rs:156"
    },
    {
      "route": "get_verdict_checkpoints",
      "field": "items",
      "source": "gx-api/src/verdict_checkpoints.rs:249"
    },
    {
      "route": "get_verdict_checkpoints",
      "field": "next_cursor",
      "source": "gx-api/src/verdict_checkpoints.rs:250"
    },
    {
      "route": "get_verdict_checkpoints",
      "field": "total",
      "source": "gx-api/src/verdict_checkpoints.rs:253"
    },
    {
      "route": "get_ledger_consistency",
      "field": "consistent",
      "source": "gx-api/src/list.rs:498"
    },
    {
      "route": "get_ledger_consistency",
      "field": "checked_from",
      "source": "gx-api/src/list.rs:504"
    },
    {
      "route": "get_ledger_consistency",
      "field": "checked_to",
      "source": "gx-api/src/list.rs:505"
    }
  ]
};
